[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aave/core-v3/contracts/=lib/aave-v3-core/contracts",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts",
    "@gho/gho-core/contracts/=lib/gho-core/src/contracts",
    "@chainlink/contracts/=node_modules/@chainlink/contracts",
    "@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
